import{Entity, Column, PrimaryGeneratedColumn} from 'typeorm'
// TypeORM is an Object Relational Mapping (ORM) tool that allows you to interact with a database using objects, rather than writing raw SQL queries.


@Entity()
// the @Entity annotation is used to mark a class as an entity, which is a representation of a database table.
export class Quote {
    //it is the primary key of the entity, it specifies that the column should be auto-incrementing, It indicates that the value of the column is generated by the database, rather than being provided by the application.
    @PrimaryGeneratedColumn()
    id: number;
//is used to define a column in a database table.@Column
    @Column({ type: 'string', length: 255, nullable: false })
    quoteText: string;
}

// By using the @Column annotation, you're telling TypeORM to create a column in the database table with the specified properties and data type.